name: Run Comparison (with Charts)

on:
  workflow_dispatch:
    inputs:
      file_2024:
        description: 'Excel 2024'
        required: false
        default: 'data/arrecadacao_liquida_jan_dez_2024.xlsx'
      file_2025:
        description: 'Excel 2025 (modelo/ordem)'
        required: false
        default: 'data/arrecadacao_jan_jul_2025.xlsx'
      out_xlsx:
        description: 'Arquivo Excel de saída'
        required: false
        default: 'out/comparativo_receitas_2024_2025_1S.xlsx'
      out_dir:
        description: 'Diretório de saída'
        required: false
        default: 'out'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run comparison + charts
        run: |
          python compare_semesters.py \
            --file-2024 "${{ github.event.inputs.file_2024 }}" \
            --file-2025 "${{ github.event.inputs.file_2025 }}" \
            --out-xlsx "${{ github.event.inputs.out_xlsx }}" \
            --out-dir "${{ github.event.inputs.out_dir }}"

      - name: Upload artifact (Excel + PDF + Charts)
        uses: actions/upload-artifact@v4
        with:
          name: comparativo_receitas_2024_2025_1S
          path: |
            ${{ github.event.inputs.out_xlsx }}
            ${{ github.event.inputs.out_dir }}/relatorio_comparativo_1S_2024_2025.pdf
            ${{ github.event.inputs.out_dir }}/charts/**
